name: kite_group_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.2
  flutter_sim_country_code: ^0.1.2
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  firebase_remote_config: ^3.0.6
  firebase_analytics: ^10.0.7
  root_access: ^1.0.4
  advertising_id: ^2.4.0
  appmetrica_plugin: ^1.1.0
  device_info_plus: ^8.1.0
  battery_info: ^1.1.1
  carrier_info_v3: ^1.0.0
  shared_preferences: ^2.0.17
  firebase_crashlytics: ^3.0.14
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.2.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
flutter_icons:

  image_path: "assets/11.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

